### ISSUE TITLE
Add option to open [filename] with O_CREAT

### ISSUE THREAD

**Issue by nil0x42** [ysf/anewer#7]
by default, `anew` opens file with O_CREAT. despite liking anewer's behavior of failing i file doesn't exist, it would be nice to have a flag `-c, --create` to be able to ask `anewer` to create the file if it doesn't exist yet

**Comment by kpcyrd** [comment]
Hey! Can you try #6?

**Comment by nil0x42** [comment]
Nice :+1: , i was also about to post another issue about the newline
